### ISSUE TITLE
Adding ssh keys to root user

### ISSUE THREAD

**Issue by seavba** [freehck/ansible-role-user-func#3]
Hi,

I tried to add ssh keys in /root/.ssh/authorized_keys and it was creating /home/root...

**Comment by seavba** [comment]
I tried to push a new branch with my changes but I don't have rights.

```
- name: Check if user is root
  set_fact:
    home: "/root"
  when: username == "root"
- name: Check if user is root
  set_fact:
    home: "/home/{{ username }}"
  when: username != "root"
```

And then I changed paths by 
`path: "{{home}}/.ssh"`

Can I have rights on this repo please?
